# import anything?

TILE_WIDTH = 32
GAMEMAP_TILES_WIDE = 19
GAMEMAP_TILES_HIGH = 15

# window constants (16:9)
TILE_ZOOM = 1 # eventually go 2 here
WIN_WIDTH = 960 * TILE_ZOOM
WIN_HEIGHT = 540 * TILE_ZOOM

# map info and draw constants
ZOOMED_WIDTH = TILE_WIDTH * TILE_ZOOM
TILEMAP_WIDTH_IN_TILES = 8
TILEMAP_FRAMES_PER_ANIMATION = 16

# gamemap constants
GAMEMAP_SCREEN_Y = (WIN_HEIGHT - GAMEMAP_TILES_HIGH * TILE_WIDTH * TILE_ZOOM) // 2
GAMEMAP_SCREEN_X = WIN_WIDTH - GAMEMAP_TILES_WIDE * TILE_WIDTH * TILE_ZOOM - GAMEMAP_SCREEN_Y
print(
	GAMEMAP_SCREEN_X, GAMEMAP_SCREEN_Y, 
	'->',
	GAMEMAP_SCREEN_X+(TILE_WIDTH*GAMEMAP_TILES_WIDE), GAMEMAP_SCREEN_Y+(TILE_WIDTH*GAMEMAP_TILES_HIGH)
)
# ^^ default Y = (540 - 15 * 32)//2 = 30; X = 960 - 19 * 32 - 30 = 322
# gamemap X[322 -> 802]; Y[30 -> 510]

# physics constants
PLAYER_MAXSPEED = 18.0 * TILE_WIDTH
PLAYER_MINSPEED_SQ = 1.0
PLAYER_MAXSPEED_SQ = PLAYER_MAXSPEED**2

PLAYER_FRICTION = 0.1 * PLAYER_MAXSPEED
PLAYER_ACCEL = 0.03 * PLAYER_MAXSPEED_SQ
PLAYER_FOLLOWINGDIST = TILE_WIDTH * 1.2
PLAYER_FOLLOWINGEPSILON	 = TILE_WIDTH * 0.15

# misc constants
FRAMERATE_LOCK = 144
PHYSICS_TIME_STEP = 1.0/100